# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/tconbeer/sqlfmt
    rev: 07e326fc2d2acf4f5a041397717f17db6b66af79  # frozen: v0.26.0
    hooks:
    -   id: sqlfmt
        language_version: python
        additional_dependencies: ['.[jinjafmt]']
