version: '3'
includes:
  env_checks:
    taskfile: ./env_checks.yml
    internal: true
tasks:
  # dbt
  get_samples:
    desc: "Get sample data for dbt"
    dir: ./dbt
    cmds:
      - "uv run dbt run-operation create_all_samples --args '{source_schema: foreign_raw}' --target dev_samples"
      - "uv run dbt run-operation create_all_samples --args '{source_schema: foreign_raw}' --target test_samples"
    preconditions:
      - task: env_checks:check_dbt
      - task: env_checks:check_dbt_initialized
      - task: env_checks:check_dbt_db_online
      - task: env_checks:check_data_status
