version: '3'
includes:
  env_checks:
    taskfile: ./env_checks.yml
    internal: true
tasks:
  # dbt
  get_samples:
    desc: "Get sample data for dbt"
    dir: ./dbt
    cmds:
      - "uv run dbt run-operation sample_by_id_variable_rows --args '{indexed_column: id, sample_target_output: sample-dev}' --target sample-dev"
      - "uv run dbt run-operation sample_by_id_variable_rows --args '{indexed_column: id, sample_target_output: sample-test}' --target sample-test"
    preconditions:
      - task: env_checks:check_dbt
      - task: env_checks:check_dbt_initialized
      - task: env_checks:check_dbt_db_online
      - task: env_checks:check_data_status
