site_name: Data Analytics Stack

theme:
  name: "material"
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

nav:
  - Home: index.md
  - Chapter 1: chapter_01.md
  - Chapter 2: chapter_02.md
  - Chapter 3: chapter_03.md
  - Chapter 4: chapter_04.md
  - Chapter 5: chapter_05.md
  - Appendix: appendix.md
