name: CI_pipeline
on:
  pull_request:
    branches:
      - master
jobs:
  CI_jobs:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
      DBT_PROFILES_DIR: ${{ secrets.DBT_PROFILES_DIR }}
      DBT_PROJECT_DIR: ${{ secrets.DBT_PROJECT_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Changed Files
        id: file_changes
        uses: tj-actions/changed-files@v46.0.3

      - name: Check env var GITHUB_CONTEXT
        run: echo '${{ toJson(github) }}'

      - name: Print info
        run: |
          echo PR number: "$GITHUB_PR_NUMBER"
          echo Changed files: '${{ steps.file_changes.outputs.all_changed_files}}'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install python
        run: uv python install

      - name: Install project dependencies
        run: uv sync

      - name: Install CI group dependencies
        run: uv sync --group ci

      #### LINTING ####
      - name: Run sqlfmt
        run: uv run sqlfmt --diff ${{ steps.file_changes.outputs.all_changed_files }}
      - name: Run ruff lint
        run: uv run ruff check --output-format=github ${{ steps.file_changes.outputs.all_changed_files }}
      - name: Run isort
        run: uv run isort --check-only ${{ steps.file_changes.outputs.all_changed_files }}

      - name: dbt Install dependencies
        run: |
          uv run dbt deps

      - name: dbt Test connection
        run: |
          uv run dbt debug --target test

      - name: dbt Build in test
        run: |
          uv run dbt build -s "state:modified+" --target test --state ./target

      - name: dbt Generate documentation
        run: |
          uv run dbt docs generate --target test
