name: Show GitHub context
on: workflow_dispatch
jobs:
  dev_jobs:
    runs-on: ubuntu-latest
    env: 
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Check env var GITHUB_CONTEXT
        run: echo "$GITHUB_CONTEXT"
