name: show_github_context
on: workflow_dispatch
jobs:
  dev_jobs:
    runs-on: self-hosted
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check env var GITHUB_CONTEXT
        run: echo "$GITHUB_CONTEXT"
